/*
 Navicat Premium Data Transfer

 Source Server         : Aliyun
 Source Server Type    : MySQL
 Source Server Version : 50731
 Source Host           : 120.78.95.212:3306
 Source Schema         : petshop

 Target Server Type    : MySQL
 Target Server Version : 50731
 File Encoding         : 65001

 Date: 25/03/2021 07:21:43
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for messages
-- ----------------------------
DROP TABLE IF EXISTS `messages`;
CREATE TABLE `messages`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sender` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `header` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `receiver` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `message` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `time` int(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 120 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of messages
-- ----------------------------
INSERT INTO `messages` VALUES (103, 'admin', 'images/male-3.png', 'admin、test', 'Create successfully, start chat', 1616514240);
INSERT INTO `messages` VALUES (110, 'test', 'images/male-2.png', 'test、test', 'Create successfully, start chat', 1616514457);
INSERT INTO `messages` VALUES (105, 'test', 'images/male-2.png', 'admin、test', '你好\n', 1616514264);
INSERT INTO `messages` VALUES (106, 'test', 'images/male-2.png', 'admin、test', 'test\n', 1616514272);
INSERT INTO `messages` VALUES (107, 'test', 'images/male-2.png', 'admin、test', 'ggg', 1616514280);
INSERT INTO `messages` VALUES (108, 'admin', 'images/male-3.png', 'admin、test', 'yes\n', 1616514291);
INSERT INTO `messages` VALUES (111, 'test', 'images/male-2.png', 'admin、test', 'laile、\n', 1616514472);
INSERT INTO `messages` VALUES (112, 'admin', 'images/male-3.png', 'admin、test', 'nen\n', 1616514487);
INSERT INTO `messages` VALUES (113, 'test', 'images/male-2.png', 'admin、test', 'anye\n', 1616514496);
INSERT INTO `messages` VALUES (114, 'test', 'images/male-2.png', 'test、yaphp', 'Create successfully, start chat', 1616514551);
INSERT INTO `messages` VALUES (115, 'test', 'images/male-2.png', 'test、yaphp', 'wenwen\n', 1616514561);
INSERT INTO `messages` VALUES (116, 'test', 'images/male-2.png', 'test、yaphp', 'qita\n', 1616514569);
INSERT INTO `messages` VALUES (117, 'Di', 'images/male-5.png', 'Di、Di', 'Create successfully, start chat', 1616544434);
INSERT INTO `messages` VALUES (118, 'Di', 'images/male-5.png', 'Di、Di', '', 1616544749);
INSERT INTO `messages` VALUES (119, 'Di', 'images/male-5.png', 'Di、Di', 'df', 1616544753);

-- ----------------------------
-- Table structure for orders
-- ----------------------------
DROP TABLE IF EXISTS `orders`;
CREATE TABLE `orders`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uid` int(11) NULL DEFAULT NULL,
  `pid` int(11) NULL DEFAULT NULL,
  `price` decimal(10, 2) NULL DEFAULT NULL,
  `phone` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `status` int(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 58 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of orders
-- ----------------------------
INSERT INTO `orders` VALUES (56, 1, 1, 800.00, '123', '123', 0);
INSERT INTO `orders` VALUES (57, 2, 103, 100.00, '123123', '123123', 0);

-- ----------------------------
-- Table structure for pets
-- ----------------------------
DROP TABLE IF EXISTS `pets`;
CREATE TABLE `pets`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uid` int(11) NULL DEFAULT NULL,
  `title` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `type` int(1) NULL DEFAULT NULL,
  `breed` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `oname` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `cover` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `descr` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `price` decimal(10, 2) NULL DEFAULT NULL,
  `views` int(8) NULL DEFAULT 0,
  `area` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `delivery` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 104 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of pets
-- ----------------------------
INSERT INTO `pets` VALUES (1, 1, '\r\nBeautiful white puppet cat1', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (2, 1, '\r\nBeautiful white puppet cat2', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 912, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (3, 1, '\r\nBeautiful white puppet cat3', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (4, 1, '\r\nBeautiful white puppet cat4', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (5, 1, '\r\nBeautiful white puppet cat5', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 912, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (6, 1, '\r\nBeautiful white puppet cat6', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (7, 1, '\r\nBeautiful white puppet cat7', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (8, 1, '\r\nBeautiful white puppet cat8', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (9, 1, '\r\nBeautiful white puppet cat9', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (10, 1, '\r\nBeautiful white puppet cat10', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (11, 1, '\r\nAbyssinian cat11', 1, 'Abyssinian', 'Aby', '/dist/images/aby.jpg', 'Abyssinians are highly intelligent and intensely inquisitive. They love to investigate and will leave no nook or cranny unexplored. They’re sometimes referred to as “Aby-grabbys” because they tend to take things that grab their interest. The playful Aby loves to jump and climb. Keep a variety of toys on hand to keep her occupied, including puzzle toys that challenge her intelligence.', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (12, 1, '\r\nAbyssinian cat12', 1, 'Abyssinian', 'Aby', '/dist/images/aby.jpg', 'Abyssinians are highly intelligent and intensely inquisitive. They love to investigate and will leave no nook or cranny unexplored. They’re sometimes referred to as “Aby-grabbys” because they tend to take things that grab their interest. The playful Aby loves to jump and climb. Keep a variety of toys on hand to keep her occupied, including puzzle toys that challenge her intelligence.', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (13, 1, '\r\nAbyssinian cat13', 1, 'Abyssinian', 'Aby', '/dist/images/aby.jpg', 'Abyssinians are highly intelligent and intensely inquisitive. They love to investigate and will leave no nook or cranny unexplored. They’re sometimes referred to as “Aby-grabbys” because they tend to take things that grab their interest. The playful Aby loves to jump and climb. Keep a variety of toys on hand to keep her occupied, including puzzle toys that challenge her intelligence.', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (14, 1, 'Abyssinian cat14', 1, 'Abyssinian', 'Aby', '/dist/images/aby.jpg', 'Abyssinians are highly intelligent and intensely inquisitive. They love to investigate and will leave no nook or cranny unexplored. They’re sometimes referred to as “Aby-grabbys” because they tend to take things that grab their interest. The playful Aby loves to jump and climb. Keep a variety of toys on hand to keep her occupied, including puzzle toys that challenge her intelligence.', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (15, 1, 'Abyssinian cat15', 1, 'Abyssinian', 'Aby', '/dist/images/aby.jpg', 'Abyssinians are highly intelligent and intensely inquisitive. They love to investigate and will leave no nook or cranny unexplored. They’re sometimes referred to as “Aby-grabbys” because they tend to take things that grab their interest. The playful Aby loves to jump and climb. Keep a variety of toys on hand to keep her occupied, including puzzle toys that challenge her intelligence.', 800.00, 912, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (16, 1, 'Abyssinian cat16', 1, 'Abyssinian', 'Aby', '/dist/images/aby.jpg', 'Abyssinians are highly intelligent and intensely inquisitive. They love to investigate and will leave no nook or cranny unexplored. They’re sometimes referred to as “Aby-grabbys” because they tend to take things that grab their interest. The playful Aby loves to jump and climb. Keep a variety of toys on hand to keep her occupied, including puzzle toys that challenge her intelligence.', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (17, 1, 'Abyssinian cat17', 1, 'Abyssinian', 'Aby', '/dist/images/aby.jpg', 'Abyssinians are highly intelligent and intensely inquisitive. They love to investigate and will leave no nook or cranny unexplored. They’re sometimes referred to as “Aby-grabbys” because they tend to take things that grab their interest. The playful Aby loves to jump and climb. Keep a variety of toys on hand to keep her occupied, including puzzle toys that challenge her intelligence.', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (18, 1, 'Abyssinian cat18', 1, 'Abyssinian', 'Aby', '/dist/images/aby.jpg', 'Abyssinians are highly intelligent and intensely inquisitive. They love to investigate and will leave no nook or cranny unexplored. They’re sometimes referred to as “Aby-grabbys” because they tend to take things that grab their interest. The playful Aby loves to jump and climb. Keep a variety of toys on hand to keep her occupied, including puzzle toys that challenge her intelligence.', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (19, 1, 'Abyssinian cat19', 1, 'Abyssinian', 'Aby', '/dist/images/aby.jpg', 'Abyssinians are highly intelligent and intensely inquisitive. They love to investigate and will leave no nook or cranny unexplored. They’re sometimes referred to as “Aby-grabbys” because they tend to take things that grab their interest. The playful Aby loves to jump and climb. Keep a variety of toys on hand to keep her occupied, including puzzle toys that challenge her intelligence.', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (20, 1, 'Abyssinian cat20', 1, 'Abyssinian', 'Aby', '/dist/images/aby.jpg', 'Abyssinians are highly intelligent and intensely inquisitive. They love to investigate and will leave no nook or cranny unexplored. They’re sometimes referred to as “Aby-grabbys” because they tend to take things that grab their interest. The playful Aby loves to jump and climb. Keep a variety of toys on hand to keep her occupied, including puzzle toys that challenge her intelligence.', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (21, 1, '\r\nBeautiful white puppet cat21', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (22, 1, '\r\nBeautiful white puppet cat22', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (23, 1, '\r\nBeautiful white puppet cat23', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (24, 1, '\r\nBeautiful white puppet cat24', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (25, 1, '\r\nBeautiful white puppet cat25', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (26, 1, '\r\nBeautiful white puppet cat26', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (27, 1, '\r\nBeautiful white puppet cat27', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (28, 1, '\r\nBeautiful white puppet cat28', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (29, 1, '\r\nBeautiful white puppet cat29', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (30, 1, '\r\nBeautiful white puppet cat30', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (31, 1, '\r\nBeautiful white puppet cat31', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (32, 1, '\r\nBeautiful white puppet cat32', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (33, 1, '\r\nBeautiful white puppet cat33', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (34, 1, '\r\nBeautiful white puppet cat34', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (35, 1, '\r\nBeautiful white puppet cat35', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (36, 1, '\r\nBeautiful white puppet cat36', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (37, 1, '\r\nBeautiful white puppet cat37', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (38, 1, '\r\nBeautiful white puppet cat38', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (39, 1, '\r\nBeautiful white puppet cat39', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (40, 1, '\r\nBeautiful white puppet cat40', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (41, 1, '\r\nBeautiful white puppet cat41', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (42, 1, '\r\nBeautiful white puppet cat42', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (43, 1, '\r\nBeautiful white puppet cat43', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (44, 1, '\r\nBeautiful white puppet cat44', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (45, 1, '\r\nBeautiful white puppet cat45', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (46, 1, '\r\nBeautiful white puppet cat46', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (47, 1, '\r\nBeautiful white puppet cat47', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (48, 1, '\r\nBeautiful white puppet cat48', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (49, 1, '\r\nBeautiful white puppet cat49', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (50, 1, '\r\nBeautiful white puppet cat50', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (51, 1, '\r\nBeautiful white puppet cat51', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (52, 1, '\r\nBeautiful white puppet cat52', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (53, 1, '\r\nBeautiful white puppet cat53', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (54, 1, '\r\nBeautiful white puppet cat54', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (55, 1, '\r\nBeautiful white puppet cat55', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (56, 1, '\r\nBeautiful white puppet cat56', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (57, 1, '\r\nBeautiful white puppet cat57', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (58, 1, '\r\nBeautiful white puppet cat58', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (59, 1, '\r\nBeautiful white puppet cat59', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (60, 1, '\r\nBeautiful white puppet cat60', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (61, 1, '\r\nBeautiful white puppet cat61', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (62, 1, '\r\nBeautiful white puppet cat62', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (63, 1, '\r\nBeautiful white puppet cat63', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (64, 1, '\r\nBeautiful white puppet cat64', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (65, 1, '\r\nBeautiful white puppet cat65', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (66, 1, '\r\nBeautiful white puppet cat66', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (67, 1, '\r\nBeautiful white puppet cat67', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (68, 1, '\r\nBeautiful white puppet cat68', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (69, 1, '\r\nBeautiful white puppet cat69', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (70, 1, '\r\nBeautiful white puppet cat70', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (71, 1, '\r\nBeautiful white puppet cat71', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (72, 1, '\r\nBeautiful white puppet cat72', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (73, 1, '\r\nBeautiful white puppet cat73', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (74, 1, '\r\nBeautiful white puppet cat74', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (75, 1, '\r\nBeautiful white puppet cat75', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (76, 1, '\r\nBeautiful white puppet cat76', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (77, 1, '\r\nBeautiful white puppet cat77', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (78, 1, '\r\nBeautiful white puppet cat78', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (79, 1, '\r\nBeautiful white puppet cat79', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (80, 1, '\r\nBeautiful white puppet cat80', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (81, 1, '\r\nBeautiful white puppet cat81', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (82, 1, '\r\nBeautiful white puppet cat82', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (83, 1, '\r\nBeautiful white puppet cat83', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (84, 1, '\r\nBeautiful white puppet cat84', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (85, 1, '\r\nBeautiful white puppet cat85', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (86, 1, '\r\nBeautiful white puppet cat86', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (87, 1, '\r\nBeautiful white puppet cat87', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (88, 1, '\r\nBeautiful white puppet cat88', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (89, 1, '\r\nBeautiful white puppet cat89', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (90, 1, '\r\nBeautiful white puppet cat90', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (91, 1, '\r\nBeautiful white puppet cat91', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (92, 1, '\r\nBeautiful white puppet cat92', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (93, 1, '\r\nBeautiful white puppet cat93', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (94, 1, '\r\nBeautiful white puppet cat94', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (95, 1, '\r\nBeautiful white puppet cat95', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (96, 1, '\r\nBeautiful white puppet cat96', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (97, 1, '\r\nBeautiful white puppet cat97', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (98, 1, '\r\nBeautiful white puppet cat98', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (99, 1, '\r\nBeautiful white puppet cat99', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (100, 1, '\r\nBeautiful white puppet cat100', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (101, 1, '\r\nBeautiful white puppet cat101', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (102, 1, '\r\nBeautiful white puppet cat102', 1, 'Ragdoll', 'Dog-Like Cats、Puppy cats', '/dist/images/ragdoll.jpg', 'Ruppets are a breed of domestic cats with soft, long coats that need to be groomed and washed frequently to prevent knots. Breed by American Ann Baker in the 1960s, the breed gets its name because it is gentle and cuddles like a soft puppet. They are common in their native countries, the United States and the United Kingdom, where they are known as dog-like cats, puppy-like cats, or puppy-like cats because they are docile and particularly sticky', 800.00, 911, 'Trecena', '	In 1 - 5 working days');
INSERT INTO `pets` VALUES (103, 2, 'test balck cat', 1, 'black', 'xuanmao', '/dist/images/8681b225b6ab1ab40caf037eddb7bab6.jpg', '123123', 100.00, 9, 'china', '1-5 days');

-- ----------------------------
-- Table structure for user
-- ----------------------------
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `password` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `header` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `certfile` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `token` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 9 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of user
-- ----------------------------
INSERT INTO `user` VALUES (1, 'yaphp', '202cb962ac59075b964b07152d234b70', 'images/male-1.png', NULL, '678b8716baf4e71adf638a5b922ff4cb');
INSERT INTO `user` VALUES (2, 'test', '202cb962ac59075b964b07152d234b70', 'images/male-2.png', NULL, '841bba0660de934d5a932012806fd557');
INSERT INTO `user` VALUES (3, 'admin', '202cb962ac59075b964b07152d234b70', 'images/male-3.png', NULL, 'ecf153735623a6d42781516317a8efe0');
INSERT INTO `user` VALUES (4, 'dudu', '202cb962ac59075b964b07152d234b70', 'images/male-4.png', NULL, NULL);
INSERT INTO `user` VALUES (5, 'yaya', '4297f44b13955235245b2497399d7a93', 'images/male-2.png', '/dist/images/4940c6663e6c4484f9a706af7a90cc33.jpg', '43867388356ef76bfe34c17105a1568d');
INSERT INTO `user` VALUES (6, 'Di', 'c0068f08ec3232dffecac744b699333d', 'images/male-5.png', NULL, NULL);
INSERT INTO `user` VALUES (7, 'Di', '81dc9bdb52d04dc20036dbd8313ed055', 'images/male-5.png', NULL, 'de951c4017d7fe29033daf1f658d07c5');
INSERT INTO `user` VALUES (8, 'Dii', '202cb962ac59075b964b07152d234b70', 'images/male-10.png', NULL, '3d8dfe53cf1c64d49ae2f6118fdf2a37');

SET FOREIGN_KEY_CHECKS = 1;
